services:
  - type: web
    name: chat-langchain-backend
    env: python
    region: singapore
    buildCommand: pip install poetry && poetry config virtualenvs.create false && poetry install
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        sync: false
      - key: WEAVIATE_URL
        sync: false
      - key: WEAVIATE_API_KEY
        sync: false
      - key: RECORD_MANAGER_DB_URL
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: true
      - key: LANGCHAIN_ENDPOINT
        value: https://api.smith.langchain.com
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: chat-langchain-study
